# Generated by Django 5.2.10 on 2026-01-12

from django.db import migrations, models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Create Symbol model
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('CRYPTO', 'Cryptocurrency'), ('GOLD', 'Gold'), ('COMMODITY', 'Commodity'), ('FX', 'Foreign Exchange'), ('STOCK', 'Stock'), ('INDEX', 'Index')], max_length=20)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),

        # Create MarketType model
        migrations.CreateModel(
            name='MarketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SPOT', 'Spot Market'), ('PERPETUAL', 'Perpetual Futures'), ('FUTURES', 'Dated Futures'), ('CFD', 'Contract for Difference')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('supports_funding', models.BooleanField(default=False)),
                ('supports_open_interest', models.BooleanField(default=False)),
            ],
        ),

        # Create Timeframe model
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('minutes', models.IntegerField()),
                ('classification', models.CharField(choices=[('SHORT', 'Short-term (intraday to 5 days)'), ('MEDIUM', 'Medium-term (days to weeks)'), ('LONG', 'Long-term (weeks to months)')], max_length=10)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['minutes'],
            },
        ),

        # Create Feature model
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical Indicator'), ('MACRO', 'Macro Economic'), ('INTERMARKET', 'Intermarket Relationship'), ('SENTIMENT', 'Market Sentiment'), ('CRYPTO_SPOT', 'Crypto Spot Specific'), ('CRYPTO_DERIVATIVES', 'Crypto Derivatives'), ('VOLUME', 'Volume Analysis'), ('VOLATILITY', 'Volatility Metric'), ('STRUCTURE', 'Market Structure')], max_length=30)),
                ('description', models.TextField()),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('weight_short', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight_medium', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight_long', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('applicable_spot', models.BooleanField(default=True)),
                ('applicable_derivatives', models.BooleanField(default=True)),
                ('requires_crypto', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),

        # Create Decision model
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('WEAK_BUY', 'Weak Buy'), ('NEUTRAL', 'Neutral'), ('WEAK_SELL', 'Weak Sell'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=15)),
                ('bias', models.CharField(choices=[('BULLISH', 'Bullish'), ('NEUTRAL', 'Neutral'), ('BEARISH', 'Bearish')], max_length=10)),
                ('confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('risk_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invalidation_conditions', models.JSONField(blank=True, default=list)),
                ('top_drivers', models.JSONField(blank=True, default=list)),
                ('raw_score', models.FloatField(blank=True, null=True)),
                ('regime_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('market_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.markettype')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='oracle.symbol')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.timeframe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        # Create DecisionOutcome model (NEW)
        migrations.CreateModel(
            name='DecisionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Target Hit'), ('LOSS', 'Stop Hit'), ('TIMEOUT', 'Expired'), ('BREAK_EVEN', 'Break Even'), ('INVALIDATED', 'Invalidation Triggered')], default='PENDING', max_length=15)),
                ('actual_exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='P&L %', max_digits=10, null=True)),
                ('r_multiple', models.DecimalField(blank=True, decimal_places=2, help_text='R-multiple achieved', max_digits=10, null=True)),
                ('max_favorable_excursion', models.DecimalField(blank=True, decimal_places=4, help_text='Best price reached (%)', max_digits=10, null=True)),
                ('max_adverse_excursion', models.DecimalField(blank=True, decimal_places=4, help_text='Worst price reached (%)', max_digits=10, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='oracle.decision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        # Create FeatureContribution model
        migrations.CreateModel(
            name='FeatureContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.FloatField()),
                ('direction', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('strength', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('weight', models.FloatField()),
                ('contribution', models.FloatField()),
                ('explanation', models.TextField(blank=True)),
                ('calculation_time_ms', models.FloatField(blank=True, help_text='Time taken to calculate this feature', null=True)),
                ('data_quality_score', models.FloatField(blank=True, help_text='Data quality/completeness score (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_contributions', to='oracle.decision')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.feature')),
            ],
            options={
                'ordering': ['-contribution'],
            },
        ),

        # Create MarketData model
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=30)),
                ('indicators', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.markettype')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='oracle.symbol')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.timeframe')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        # Create DerivativesData model
        migrations.CreateModel(
            name='DerivativesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('funding_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('funding_rate_8h', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('next_funding_time', models.DateTimeField(blank=True, null=True)),
                ('open_interest', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('open_interest_value', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('index_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('basis', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('liquidations_long', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('liquidations_short', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives_data', to='oracle.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        # Create MacroData model
        migrations.CreateModel(
            name='MacroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        # Create SentimentData model
        migrations.CreateModel(
            name='SentimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('NEWS', 'News Articles'), ('TWITTER', 'Twitter/X'), ('REDDIT', 'Reddit'), ('TELEGRAM', 'Telegram'), ('FEAR_GREED', 'Fear & Greed Index'), ('OTHER', 'Other Source')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('score', models.FloatField()),
                ('normalized_score', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_data', to='oracle.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        # Create AnalysisRun model
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('symbols', models.JSONField(default=list)),
                ('timeframes', models.JSONField(default=list)),
                ('market_types', models.JSONField(default=list)),
                ('decisions_created', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        # Create FeatureWeight model
        migrations.CreateModel(
            name='FeatureWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.feature')),
                ('market_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oracle.markettype')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oracle.symbol')),
                ('timeframe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oracle.timeframe')),
            ],
        ),

        # Create SystemMetrics model (NEW)
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider_name', models.CharField(db_index=True, max_length=50)),
                ('provider_uptime_percentage', models.FloatField(blank=True, help_text='Provider uptime in last 24h (%)', null=True)),
                ('provider_avg_latency_ms', models.FloatField(blank=True, help_text='Average latency in milliseconds', null=True)),
                ('provider_error_count', models.IntegerField(default=0)),
                ('provider_success_count', models.IntegerField(default=0)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('cpu_usage_percentage', models.FloatField(blank=True, null=True)),
                ('celery_queue_depth', models.IntegerField(blank=True, help_text='Number of pending tasks', null=True)),
                ('celery_active_workers', models.IntegerField(blank=True, null=True)),
                ('celery_failed_tasks_24h', models.IntegerField(blank=True, null=True)),
                ('slow_query_count', models.IntegerField(default=0, help_text='Queries >100ms in last hour')),
                ('avg_query_time_ms', models.FloatField(blank=True, null=True)),
                ('total_queries', models.IntegerField(default=0)),
                ('feature_calculation_errors', models.IntegerField(default=0)),
                ('avg_feature_calc_time_ms', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        # Create SymbolPerformance model
        migrations.CreateModel(
            name='SymbolPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('roi_1h', models.DecimalField(blank=True, decimal_places=4, help_text='1 hour ROI %', max_digits=10, null=True)),
                ('roi_1d', models.DecimalField(blank=True, decimal_places=4, help_text='1 day ROI %', max_digits=10, null=True)),
                ('roi_1w', models.DecimalField(blank=True, decimal_places=4, help_text='1 week ROI %', max_digits=10, null=True)),
                ('roi_1m', models.DecimalField(blank=True, decimal_places=4, help_text='1 month ROI %', max_digits=10, null=True)),
                ('roi_1y', models.DecimalField(blank=True, decimal_places=4, help_text='1 year ROI %', max_digits=10, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('volume_change_24h', models.DecimalField(blank=True, decimal_places=4, help_text='24h volume change %', max_digits=10, null=True)),
                ('volatility_24h', models.DecimalField(blank=True, decimal_places=4, help_text='24h volatility %', max_digits=10, null=True)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
                ('trades_24h', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('market_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle.markettype')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='oracle.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        # Add indexes
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['asset_type', 'is_active'], name='oracle_symb_asset_t_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['category', 'is_active'], name='oracle_feat_categor_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['name'], name='oracle_feat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['symbol', 'market_type', 'timeframe', '-created_at'], name='oracle_deci_symbol__idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['signal', '-created_at'], name='oracle_deci_signal__idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['confidence', '-created_at'], name='oracle_deci_confide_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['bias', '-created_at'], name='oracle_deci_bias_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionoutcome',
            index=models.Index(fields=['outcome', '-created_at'], name='oracle_deci_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionoutcome',
            index=models.Index(fields=['decision', 'outcome'], name='oracle_deci_decisio_idx'),
        ),
        migrations.AddIndex(
            model_name='featurecontribution',
            index=models.Index(fields=['decision', '-contribution'], name='oracle_feat_decisio_idx'),
        ),
        migrations.AddIndex(
            model_name='featurecontribution',
            index=models.Index(fields=['feature'], name='oracle_feat_feature_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['symbol', 'market_type', 'timeframe', '-timestamp'], name='oracle_mark_symbol__idx'),
        ),
        migrations.AddIndex(
            model_name='derivativesdata',
            index=models.Index(fields=['symbol', '-timestamp'], name='oracle_deri_symbol__idx'),
        ),
        migrations.AddIndex(
            model_name='macrodata',
            index=models.Index(fields=['indicator_name', '-timestamp'], name='oracle_macr_indicat_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentdata',
            index=models.Index(fields=['symbol', 'source', '-timestamp'], name='oracle_sent_symbol__idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['-created_at', 'status'], name='oracle_anal_created_idx'),
        ),
        migrations.AddIndex(
            model_name='featureweight',
            index=models.Index(fields=['feature', 'symbol', 'market_type', 'timeframe'], name='oracle_feat_feature_smtf_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['provider_name', '-timestamp'], name='oracle_syst_provide_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['-timestamp'], name='oracle_syst_timesta_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolperformance',
            index=models.Index(fields=['symbol', '-timestamp'], name='oracle_symp_symbol__idx'),
        ),
        migrations.AddIndex(
            model_name='symbolperformance',
            index=models.Index(fields=['symbol', 'market_type', '-timestamp'], name='oracle_symp_symbol_mt_idx'),
        ),

        # Add unique constraints
        migrations.AlterUniqueTogether(
            name='decision',
            unique_together={('symbol', 'market_type', 'timeframe', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('symbol', 'market_type', 'timeframe', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='derivativesdata',
            unique_together={('symbol', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='macrodata',
            unique_together={('indicator_name', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='featureweight',
            unique_together={('feature', 'symbol', 'market_type', 'timeframe')},
        ),
    ]
